name: test
于:
  工作流程调度:
  日程:
    # IMPORTANT: Set cr关于 job 在 UTC timezone
    - cron:  '0 18 * * *'

jobs:
  run-python-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        包含:
          python-version: '3.11'
      - run: pip install requests
      - run: python src/time.py
      
