import requests
import sys
import time
import random

def printer(info, *args):
    at_now = int(time.time())
    time_arr = time.localtime(at_now)
    format_time = time.strftime("%Y-%m-%d %H:%M:%S", time_arr)
    content = f'[{format_time}] {info} {" ".join(str(arg) for arg in args)}'
    print(content, flush=True)

def pay_order(order_id: str, token: str):
    url = "https://console.diylink.net/api/user/settlement/order-pay"
    data = {
        "discount_type": "gift",
        "coupon_code": "",
        "order_id": order_id,
        "payment": "cash_balance",
        "return_url": "/settlement/order"
    }
    headers = {
        "accept": "application/json, text/plain, */*",
        "accept-language": "zh-TW",
        "token": token,
        "origin": "https://console.diylink.net",
        "referer": f"https://console.diylink.net/settlement/pay?code={order_id}&url=/settlement/order&serviceName=virtual_machine_create",
        "user-agent": "your user_agent"
    }
    try:
        response = requests.put(url, headers=headers, data=data, proxies=None, verify=True).json()
        printer(response)
        """
        {'code': 200, 'msg': '支付成功', 'data': {'id': xx, 'sn': 'x', 'url': ''}}
        {'code': 300, 'msg': '庫存不足，如需購買更多，請次日再來。', 'data': []}
        {'code': 300, 'msg': '訂單已取消', 'data': []}
        """
        if response['code'] != 200:
            sys.exit()

        if response['msg'] == "訂單已取消":
            sys.exit()

    except Exception as e:
        print(e)
        sys.exit()

if __name__ == '__main__':
    while True:
        pay_order("12597", "e0580f6a7deaee06835de373e6e6771bh9mrEk")
        time.sleep(round(random.uniform(60 * 5, 60 * 8), 4))
